apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31186
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 31753
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerSourceRanges:
    - {{ .Values.allowedIpRange }}